const simpleResponse = {
    aggregationPayload: {},
    counter: 0,
    currentPage: 1,
    filteredRecordCount: 22,
    payload: [
        {
            OrderID: 1,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 300.0,
        },
        {
            OrderID: 2,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
            Amount: 9.0,
        },
        {
            OrderID: 3,
            CustomerName: 'Unosquare LLC',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 4,
            CustomerName: 'Vesta',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
        {
            OrderID: 5,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 174.0,
        },
        {
            OrderID: 6,
            CustomerName: 'OXXO',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 7,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
        {
            OrderID: 8,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 15.0,
        },
        {
            OrderID: 9,
            CustomerName: 'OXXO',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 10,
            CustomerName: 'Vesta',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
    ],
    totalPages: 3,
    totalRecordCount: 22,
};

const pageSize20Response = {
    aggregationPayload: {},
    counter: 3,
    currentPage: 1,
    filteredRecordCount: 22,
    payload: [
        {
            OrderID: 1,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 300.0,
        },
        {
            OrderID: 2,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
            Amount: 9.0,
        },
        {
            OrderID: 3,
            CustomerName: 'Unosquare LLC',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 4,
            CustomerName: 'Vesta',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
        {
            OrderID: 5,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 174.0,
        },
        {
            OrderID: 6,
            CustomerName: 'OXXO',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 7,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
        {
            OrderID: 8,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 15.0,
        },
        {
            OrderID: 9,
            CustomerName: 'OXXO',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 10,
            CustomerName: 'Vesta',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
        {
            OrderID: 11,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 16.0,
        },
        {
            OrderID: 12,
            CustomerName: 'OXXO',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 13,
            CustomerName: 'Unosquare LLC',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
        {
            OrderID: 14,
            CustomerName: 'Vesta',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 60.0,
        },
        {
            OrderID: 15,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Portland, OR, US',
            Amount: 192.0,
        },
        {
            OrderID: 16,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 300.0,
        },
        {
            OrderID: 17,
            CustomerName: 'Unosquare LLC',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 108.0,
        },
        {
            OrderID: 18,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
            Amount: 92.0,
        },
        {
            OrderID: 19,
            CustomerName: 'Vesta',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 300.0,
        },
        {
            OrderID: 20,
            CustomerName: 'OXXO',
            ShippedDate: '2016-11-04T18:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 78.0,
        },
    ],
    totalPages: 2,
    totalRecordCount: 22,
};

const simpleRecordsExpected = {
    aggregationPayload: { CustomerName: 500 },
    counter: 0,
    currentPage: 1,
    filteredRecordCount: 500,
    payload: [
        {
            Amount: 300,
            CustomerName: 'Microsoft',
            OrderID: 1,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: '',
            CustomerName: 'Microsoft',
            OrderID: 2,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Microsoft',
            OrderID: 3,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: '',
            CustomerName: 'Unosquare LLC',
            OrderID: 4,
            ShippedDate: '2016-02-01T18:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
        },
        {
            Amount: 92,
            CustomerName: 'Microsoft',
            OrderID: 5,
            ShippedDate: '2016-11-10T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 18,
            CustomerName: 'Unosquare LLC',
            OrderID: 6,
            ShippedDate: '2016-11-06T18:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
        },
        {
            Amount: 50,
            CustomerName: 'Unosquare LLC',
            OrderID: 7,
            ShippedDate: '2016-11-11T18:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 9,
            CustomerName: 'Unosquare LLC',
            OrderID: 8,
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
        {
            Amount: 108,
            CustomerName: 'Vesta',
            OrderID: 9,
            ShippedDate: '2016-11-07T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 15,
            CustomerName: 'Unosquare LLC',
            OrderID: 10,
            ShippedDate: '2016-11-05T18:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
    ],
    totalPages: 50,
    totalRecordCount: 500,
};

const searchTextMicrosoftResponse = {
    aggregationPayload: {},
    counter: 1,
    currentPage: 1,
    filteredRecordCount: 5,
    payload: [
        {
            Amount: 300,
            CustomerName: 'Microsoft',
            OrderID: 1,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 9,
            CustomerName: 'Microsoft',
            OrderID: 2,
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
        },
        {
            Amount: 16,
            CustomerName: 'Microsoft',
            OrderID: 11,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Microsoft',
            OrderID: 16,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 92,
            CustomerName: 'Microsoft',
            OrderID: 18,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
        },
    ],
    totalPages: 1,
    totalRecordCount: 22,
};

const page2Response = {
    aggregationPayload: {},
    counter: 2,
    currentPage: 2,
    filteredRecordCount: 22,
    payload: [
        {
            OrderID: 11,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 16.0,
        },
        {
            OrderID: 12,
            CustomerName: 'OXXO',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 92.0,
        },
        {
            OrderID: 13,
            CustomerName: 'Unosquare LLC',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 300.0,
        },
        {
            OrderID: 14,
            CustomerName: 'Vesta',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 60.0,
        },
        {
            OrderID: 15,
            CustomerName: 'Super La Playa',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Portland, OR, US',
            Amount: 192.0,
        },
        {
            OrderID: 16,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 300.0,
        },
        {
            OrderID: 17,
            CustomerName: 'Unosquare LLC',
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
            Amount: 108.0,
        },
        {
            OrderID: 18,
            CustomerName: 'Microsoft',
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
            Amount: 92.0,
        },
        {
            OrderID: 19,
            CustomerName: 'Vesta',
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
            Amount: 300.0,
        },
        {
            OrderID: 20,
            CustomerName: 'OXXO',
            ShippedDate: '2016-11-04T18:00:00',
            ShipperCity: 'Portland, OR, USA',
            Amount: 78.0,
        },
    ],
    totalPages: 3,
    totalRecordCount: 22,
};

const descendingOrderIdResponse = {
    aggregationPayload: {},
    counter: 4,
    currentPage: 1,
    filteredRecordCount: 22,
    payload: [
        {
            Amount: 150,
            CustomerName: 'Google',
            OrderID: 22,
            ShippedDate: '2016-01-04T18:00:00',
            ShipperCity: 'Monterrey, NL, Mexico',
        },
        {
            Amount: 100,
            CustomerName: 'Apple',
            OrderID: 21,
            ShippedDate: '2015-11-04T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 78,
            CustomerName: 'OXXO',
            OrderID: 20,
            ShippedDate: '2016-11-04T18:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
        {
            Amount: 300,
            CustomerName: 'Vesta',
            OrderID: 19,
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 92,
            CustomerName: 'Microsoft',
            OrderID: 18,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
        },
        {
            Amount: 108,
            CustomerName: 'Unosquare LLC',
            OrderID: 17,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Microsoft',
            OrderID: 16,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 192,
            CustomerName: 'Super La Playa',
            OrderID: 15,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Portland, OR, US',
        },
        {
            Amount: 60,
            CustomerName: 'Vesta',
            OrderID: 14,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Unosquare LLC',
            OrderID: 13,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
    ],
    totalPages: 3,
    totalRecordCount: 22,
};

const aggregateCountResponse = {
    ...simpleResponse,
    aggregationPayload: { CustomerName: 22 },
    counter: 5,
};

const aggregateSumResponse = {
    ...simpleResponse,
    aggregationPayload: { Amount: 3462 },
    counter: 6,
};

const aggregateAverageResponse = {
    ...simpleResponse,
    aggregationPayload: { Amount: 157.36363636363637 },
    counter: 7,
};

const aggregateDistinctResponse = {
    ...simpleResponse,
    aggregationPayload: { Amount: 12 },
    counter: 8,
};

const aggregateMaxResponse = {
    ...simpleResponse,
    aggregationPayload: { Amount: 300 },
    counter: 9,
};

const aggregateMinResponse = {
    ...simpleResponse,
    aggregationPayload: { Amount: 9 },
    counter: 10,
};

const pageMinus1Response = {
    aggregationPayload: {},
    counter: 11,
    currentPage: 0,
    filteredRecordCount: 22,
    payload: [
        {
            Amount: 300,
            CustomerName: 'Microsoft',
            OrderID: 1,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 9,
            CustomerName: 'Microsoft',
            OrderID: 2,
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
        },
        {
            Amount: 92,
            CustomerName: 'Unosquare LLC',
            OrderID: 3,
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Vesta',
            OrderID: 4,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
        {
            Amount: 174,
            CustomerName: 'Super La Playa',
            OrderID: 5,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 92,
            CustomerName: 'OXXO',
            OrderID: 6,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Super La Playa',
            OrderID: 7,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
        {
            Amount: 15,
            CustomerName: 'Super La Playa',
            OrderID: 8,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 92,
            CustomerName: 'OXXO',
            OrderID: 9,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Vesta',
            OrderID: 10,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
        {
            Amount: 16,
            CustomerName: 'Microsoft',
            OrderID: 11,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 92,
            CustomerName: 'OXXO',
            OrderID: 12,
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 300,
            CustomerName: 'Unosquare LLC',
            OrderID: 13,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
        {
            Amount: 60,
            CustomerName: 'Vesta',
            OrderID: 14,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 192,
            CustomerName: 'Super La Playa',
            OrderID: 15,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Portland, OR, US',
        },
        {
            Amount: 300,
            CustomerName: 'Microsoft',
            OrderID: 16,
            ShippedDate: '2016-03-19T19:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 108,
            CustomerName: 'Unosquare LLC',
            OrderID: 17,
            ShippedDate: '2016-04-23T10:00:00',
            ShipperCity: 'Leon, GTO, Mexico',
        },
        {
            Amount: 92,
            CustomerName: 'Microsoft',
            OrderID: 18,
            ShippedDate: '2016-12-22T08:00:00',
            ShipperCity: 'Los Angeles, CA, USA',
        },
        {
            Amount: 300,
            CustomerName: 'Vesta',
            OrderID: 19,
            ShippedDate: '2016-11-08T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            Amount: 78,
            CustomerName: 'OXXO',
            OrderID: 20,
            ShippedDate: '2016-11-04T18:00:00',
            ShipperCity: 'Portland, OR, USA',
        },
        {
            Amount: 100,
            CustomerName: 'Apple',
            OrderID: 21,
            ShippedDate: '2015-11-04T18:00:00',
            ShipperCity: 'Guadalajara, JAL, Mexico',
        },
        {
            OrderID: 22,
            CustomerName: 'Google',
            ShippedDate: '2016-01-04T18:00:00',
            ShipperCity: 'Monterrey, NL, Mexico',
            Amount: 150.0,
        },
    ],
    totalPages: 1,
    totalRecordCount: 22,
};

export {
    aggregateAverageResponse,
    aggregateCountResponse,
    aggregateDistinctResponse,
    aggregateMaxResponse,
    aggregateMinResponse,
    aggregateSumResponse,
    descendingOrderIdResponse,
    simpleResponse,
    searchTextMicrosoftResponse,
    pageMinus1Response,
    page2Response,
    simpleRecordsExpected,
    pageSize20Response,
};
